### PR TITLE
change the concept of getting the categories first the show the titles

### PR DESCRIPTION
**Pull request by DwinaTech**

### CODE REVIEW

**Comment by DwinaTech** [comment]
[The site is not defaulting to English when localStorage is empty](https://trello.com/c/3yma4tIX/150-the-site-is-not-defaulting-to-english-when-localstorage-is-empty)

**Review by kabaros — COMMENTED** [review]
what are you trying to do here?

**Comment by DwinaTech** [comment]
Before I changed the code there was conditiona to select the language before get categories  so I changed that is way to get categories first then check the language and I checked that worked well on developer tool after I cleared local data

**Review by kabaros — COMMENTED** [review]
all is needed for this is to default to English if no language is provided - changing the order of when state is set doesn't make a difference.

`         let language = localStorage.getItem("language") || 'en';
`

**Review by kabaros — APPROVED** [review]

**Pull request merged**
